### ISSUE TITLE
I have a pyranges library

### ISSUE THREAD

**Issue by endrebak** [alastair-droop/seqBlocks#1]
I already took the name at PyPI.

https://github.com/endrebak/pyranges

It seems to have much of the same functionality though :) If you are interested in collaborating, I'm up for suggestions.

Just a heads-up :)

**Comment by alastair-droop** [comment]
Thanks! I didn't check as this is code that I didn't think would make PyPI for some time.

* I'll come up with another name for my efforts; however
* The aim for my code is quite different from your (very interesting and useful) codebase.

Thanks again, and yes, I'd be more than delighted to share effort in the future.

**Comment by endrebak** [comment]
I learnt something new from your codebase though. Did not know about `property`.
